# Generated by Django 3.2.4 on 2021-06-26 06:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adv_backend_trainee_assignment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='creation_datetime',
            field=models.CharField(default=datetime.datetime(2021, 6, 26, 6, 15, 6, 952033), max_length=100),
        ),
    ]
