# Generated by Django 3.2.4 on 2021-06-26 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adv_backend_trainee_assignment', '0002_ad_creation_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='creation_datetime',
            field=models.CharField(max_length=100),
        ),
    ]
