# Generated by Django 3.2.4 on 2021-06-26 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adv_backend_trainee_assignment', '0003_alter_ad_creation_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='creation_datetime',
            new_name='date',
        ),
    ]
